[package]
name = "railyard"
version = "0.1.0"
edition = "2022"
default-run = "railyard"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "railyard"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
