apiVersion: apps/v1
kind: Deployment
metadata:
  name: railyard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: railyard
  template:
    metadata:
      labels:
        app: railyard
    spec:
      containers:
      - name: railyard
        image: railyard:latest
        ports:
        - containerPort: 8000
